#! /usr/bin/perl

for ($i = 0; $i < 128; $i++) {
	print "\t" unless $i % 12;
	$d = 1008000 / 16 / (440.0 * 2.0 ** (($i - 69) / 12.0));
	$d = 4095 if $d > 4095;
	printf "%d,%s", $d, $i % 12 < 11 ? " " : "\n";
}
print "\n";
exit 0;
